"""Background processing tasks and cores for player data enrichment."""

from session_sniffer.background.cores import (
    clear_resolution_queues,
    enqueue_player_for_resolution,
    ensure_looky_core_running,
    hostname_core,
    iplookup_core,
    pinger_core,
    wake_all_player_cores,
    wake_hostname_core,
    wake_iplookup_core,
    wake_looky_core,
    wake_pinger_core,
)
from session_sniffer.background.events import gui_closed__event
from session_sniffer.background.tasks import (
    NotificationConfig,
    check_global_detections,
    clear_detection_voice_notifications,
    clear_voice_notification_queue,
    ensure_voice_notification_worker_running,
    handle_detection_notification,
    is_gta5_relay_ip,
    monitor_gta5_relay_task,
    player_rates_core,
    process_userip_task,
    submit_global_detections_check,
    wait_for_player_data_ready,
)

__all__ = [
    'NotificationConfig',
    'check_global_detections',
    'clear_detection_voice_notifications',
    'clear_resolution_queues',
    'clear_voice_notification_queue',
    'enqueue_player_for_resolution',
    'ensure_looky_core_running',
    'ensure_voice_notification_worker_running',
    'gui_closed__event',
    'handle_detection_notification',
    'hostname_core',
    'iplookup_core',
    'is_gta5_relay_ip',
    'monitor_gta5_relay_task',
    'pinger_core',
    'player_rates_core',
    'process_userip_task',
    'submit_global_detections_check',
    'wait_for_player_data_ready',
    'wake_all_player_cores',
    'wake_hostname_core',
    'wake_iplookup_core',
    'wake_looky_core',
    'wake_pinger_core',
]
